language: python

python:
  - "3.6"

sudo: required

addons: 
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER_NAME=dovecot.travis.dev
    - IMAP_SERVER_PORT=993
    - IMAP_USERNAME=dovecot_travis_testuser
    - IMAP_PASSWORD=dovecot_travis_testpwd

install:
  - sh .travis/install_dovecot.sh
  - pip3 install -r requirements.txt

script:
  - python3 tests/test_proxy.py IMAP_USERNAME IMAP_PASSWORD dovecot.travis.dev