language: python

python:
  - "3.6"

sudo: required

addons: 
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER=dovecot.travis.dev
    - IMAP_USERNAME=user@dovecot.com
    - IMAP_PASSWORD=pwd
    - PROXY_PORT=8002

install:
  - pip3 install -r requirements.txt
  - sh .travis/run_imap_server.sh

before_script:
  - setsid .travis/run_proxy.sh >/dev/null 2>&1 < /dev/null &

script:
  - python3 tests/test_proxy.py "$IMAP_USERNAME" "$IMAP_PASSWORD" 0.0.0.0 -p "$PROXY_PORT"

notifications:
  email:
    on_success: change
    on_failure: change