language: python

python:
  - "3.6"

sudo: required

addons: 
  hosts:
    - dovecot.travis.dev

env:
  global:
    - SERVER=dovecot.travis.dev
    - USERNAME=user@dovecot.com
    - PASSWORD=pwd
    - PROXY_PORT=8002

install:
  - pip3 install -r requirements.txt
  - sh .travis/run_imap_server.sh

script:
  - sh .travis/run_proxy.sh &
  - python3 tests/test_proxy.py "$USERNAME" "$PASSWORD" localhost -p "$PROXY_PORT"

notifications:
  email:
    on_success: change
    on_failure: change