from lib import imaplib_noCA as imaplib
import email
import sys

# Print variables
RED = '\033[91m'
GREEN = '\033[92m'
ENDC = '\033[0m'
INFO = '[INFO]: '
SUCC = '[SUCCEED]: '
FAIL = '[FAILED]: '

""" Tests for proxy.py """

if __name__ == '__main__':

    USER = sys.argv[1]
    PASSWD = sys.argv[2]

    test_mesg = ('From: %(user)s%(lf)sSubject: IMAP4 test%(lf)s%(lf)sEmail generated by IMAProxy tests%(lf)s' % {'user':USER, 'lf':'\n'}).encode()
    test_seq1 = (
        ('login', (USER, PASSWD)),
        ('create', ('/tmp/xxx',)),
        ('rename', ('/tmp/xxx', '/tmp/yyy')),
        ('CREATE', ('/tmp/yyz',)),
        ('append', ('/tmp/yyz', None, None, test_mesg)),
        ('list', ('/tmp', 'yy*')),
        ('select', ('/tmp/yyz',)),
        ('search', (None, 'SUBJECT', 'test')),
        ('fetch', ('1', '(FLAGS INTERNALDATE RFC822)')),
        ('store', ('1', 'FLAGS', '(\Deleted)')),
        ('namespace', ()),
        ('expunge', ()),
        ('recent', ()),
        ('close', ()),
        ('delete', ('/tmp/yyz',)),
        ('delete', ('/tmp/yyy',)))

    test_seq2 = (
        # Sanitize commands
        )

    test_seq3 = (
        ('select', ()),
        ('response',('UIDVALIDITY',)),
        ('uid', ('SEARCH', 'ALL')),
        ('response', ('EXISTS',)),
        ('recent', ()),
        ('logout', ()))

    failed_tests = []
    succeed_tests = []

    def run(cmd, args):
        print(GREEN+"["+cmd+"]"+ENDC)
        typ, dat = getattr(M, cmd)(*args)
        
        if typ == 'NO': 
            failed_tests.append('%s => %s %s' % (cmd, typ, dat))
        else:
            succeed_tests.append('%s => %s %s' % (cmd, typ, dat))

        return dat

    M = imaplib.IMAP4_SSL('imap-mail.outlook.com') # We don't care about the domain name as the traffic is redirected to the proxy

    for cmd,args in test_seq1:
        run(cmd, args)

    for cmd,args in test_seq3:
        dat = run(cmd, args)

        if (cmd,args) != ('uid', ('SEARCH', 'ALL')):
            continue

        uid = dat[-1].split()
        if not uid: 
            continue

        run('uid', ('FETCH', '%s' % uid[-1].decode(),
                '(FLAGS INTERNALDATE RFC822.SIZE RFC822.HEADER RFC822.TEXT)'))

    # Display results
    if not failed_tests:
        print(GREEN+SUCC, 'TESTS SUCCEEDED', ENDC)
    else:
        print(RED+INFO, 'SOME TESTS FAILED:', ENDC)
        for test in failed_tests:
            print(FAIL, test)